### ISSUE TITLE
No warning when dataset split does not exist

### ISSUE THREAD

**Issue by PriyaTomar** [le1nux/mlgym#24]
In my config file where I define all the MLGym components and their configurations, I have defined the iterators like below. When the split `[full]` required by the `shuffled_iterator` does not exist in `isic_dataset_iterator` (which specifies train `split`), MLGym does not throws a warning or error. Adding such a feature would help in debugging the issues faster.

```
isic_dataset_iterators:
  component_type_key: DATASET_ITERATORS
  variant_key: DEFAULT
  requirements:
    - name: repository
      component_name: dataset_repository
  config:
    dataset_identifier: isic2019
    split_configs:  
        - split: train 

shuffled_iterator: 
  component_type_key: SHUFFLED_DATASET_ITERATORS
  variant_key: DEFAULT
  requirements:
    - name: iterators
      component_name: isic_dataset_iterators
      subscriptions: [full]
  config:
    seeds: {full: 42}
    applicable_splits: [full]
```
